from typing import Optional, Sequence

import numpy as np
import numpy.typing as npt

__version__: str

def version() -> str: ...
def metal_available() -> bool: ...
def cuda_available() -> bool: ...

class Device:
    @staticmethod
    def cpu() -> "Device": ...
    @staticmethod
    def metal() -> "Device": ...
    @staticmethod
    def cuda(ordinal: int) -> "Device": ...
    def is_gpu(self) -> bool: ...

class MarketData:
    def __init__(
        self,
        prices: npt.NDArray[np.float32],
        feature_names: Optional[Sequence[str]] = ...,
    ) -> None: ...
    @staticmethod
    def synthetic(timesteps: int, seed: int) -> "MarketData": ...
    def __len__(self) -> int: ...
    def num_features(self) -> int: ...

class TradingEnv:
    def __init__(
        self,
        data: MarketData,
        initial_balance: float = ...,
        transaction_cost: float = ...,
        max_position: float = ...,
        lookback: int = ...,
        episode_length: int = ...,
    ) -> None: ...
    @property
    def obs_dim(self) -> int: ...
    @property
    def act_dim(self) -> int: ...

class PPO:
    def __init__(
        self,
        env: TradingEnv,
        num_envs: int = ...,
        learning_rate: float = ...,
        n_steps: int = ...,
        batch_size: int = ...,
        n_epochs: int = ...,
        gamma: float = ...,
        hidden_sizes: Sequence[int] = ...,
        seed: Optional[int] = ...,
        device: Optional[Device] = ...,
    ) -> None: ...
    def learn(self, total_timesteps: int) -> None: ...
    def predict(
        self, observations: npt.NDArray[np.float32], deterministic: bool = ...
    ) -> npt.NDArray[np.float32]: ...
    def save(self, path: str) -> None: ...
    @property
    def act_dim(self) -> int: ...

class SAC:
    def __init__(
        self,
        env: TradingEnv,
        num_envs: int = ...,
        learning_rate: float = ...,
        batch_size: int = ...,
        buffer_size: int = ...,
        gamma: float = ...,
        seed: Optional[int] = ...,
        device: Optional[Device] = ...,
    ) -> None: ...
    def learn(self, total_timesteps: int) -> None: ...
    def predict(
        self, observations: npt.NDArray[np.float32], deterministic: bool = ...
    ) -> npt.NDArray[np.float32]: ...

class TradingMetrics:
    def __init__(self, rolling_window: int = ...) -> None: ...
    def add_returns(self, returns: npt.NDArray[np.float64]) -> None: ...
    def add_return(self, ret: float) -> None: ...
    def sharpe_ratio(self) -> float: ...
    def sortino_ratio(self) -> float: ...
    def calmar_ratio(self) -> float: ...
    def win_rate(self) -> float: ...
